combiner:
  combinations:
    - name: base
      chunks:
        - dep-cacert-update
        - tool-docker
        - tool-tailscale
    - name: node
      ref:
      - base
      chunks:
        - lang-node:17.4.0
    - name: postgresql
      ref:
      - base
      chunks:
        - tool-postgresql
  envvars:
    - name: PATH
      action: merge-unique
    - name: HOME
      action: use-last